[package]
name = "pr-comment-analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = "4.4"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }